package cn.edu.pzhu.cg.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

import org.junit.Test;

public class TestGetGeneratedKey {

	/*
	 * 获取插入记录的主键参数：
	 * 	1.创建 PreparedStatement 对象时选择 PreparedStatement(String sql,int autoGeneratedKeys) 构造函数
	 *  2.第二个参数传入 Statement.RETURN_GENERATED_KEYS
	 *  3.执行 SQL 语句后，用 getGeneratedKeys() 方法获取主键的结果集
	 *  4.结果集中的第一列数据就是主键的值
	 */
	@Test
	public void testGetKeyValue(){
		Connection conn = null;
		PreparedStatement ps = null;
		ResultSet rs = null;
		
		try {
			conn = JDBCTools.getConnection();
			String sql = "insert into student(name,age,tel,major) values(?,?,?,?)";
			ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
			
			ps.setString(1, "Jack");
			ps.setInt(2, 20);
			ps.setString(3, "13056505519");
			ps.setString(4, "土木工程");
			
			ps.executeUpdate();
			//通过 getGeneratedKeys() 获取包含了新生成的主键的 ResultSet 对象
			rs = ps.getGeneratedKeys();
			
			if(rs.next()){
				System.out.println(rs.getString(1));
			}
			
			//ResultSet 里面只有一列 GENERATED_KEY，用于存放新生成的主键值
			ResultSetMetaData rsmd = rs.getMetaData();
			for(int i = 0;i < rsmd.getColumnCount();i++){
				System.out.println(rsmd.getColumnName(i+1));
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally{
			JDBCTools.release(conn, ps, rs);
		}
	}
}
